---
- name: install k8s dependencies
  hosts: aero-slave
  become: yes
  become_user: root
  tasks:
  - name: gather os information to install the package
     setup:
      gather_subset: all
     register: osdetails
  - name: install dependencies if os is ubuntu
      apt:
        name: {{ item }}
        state: installed
        update_cache: yes
      with_items:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
  - name: add gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
  - name: add repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribu    tion_release }} stable
  - name: installation of the docker and its component
      apt:
       name: {{ item }}
       state: installed
       update_cache: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
